// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-my-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_orders_default = defineTool({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in customer's orders on Spencer's Cardtopia, most recent first. Returns id, status, total, payment method, tracking code and created date.",
  inputSchema: {
    limit: z.number().int().describe("Max number of orders to return (default 20, max 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("orders").select(
      "id,status,total,payment_method,tracking_code,shipping_label_status,created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_order_default = defineTool2({
  name: "get_my_order",
  title: "Get my order",
  description: "Return full details for one of the signed-in customer's orders, including items, totals, shipping and tracking info.",
  inputSchema: {
    orderId: z2.string().describe("The order UUID (from list_my_orders).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ orderId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("orders").select("*").eq("id", orderId).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Order not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/list-my-decks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_decks_default = defineTool3({
  name: "list_my_decks",
  title: "List my decks",
  description: "List the signed-in customer's Magic: The Gathering decks saved on Spencer's Cardtopia.",
  inputSchema: {
    includeCards: z3.boolean().describe("If true, includes the deck's card list.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeCards }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser3(ctx);
    const select = includeCards ? "id,name,format,description,created_at,updated_at,deck_cards(card_name,quantity,is_sideboard)" : "id,name,format,description,created_at,updated_at";
    const { data, error } = await client.from("decks").select(select).eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { decks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-favorites.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_favorites_default = defineTool4({
  name: "list_my_favorites",
  title: "List my favorite cards",
  description: "List cards the signed-in customer favorited on Spencer's Cardtopia.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("favorites").select("inventory_item_id,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-catalog.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_catalog_default = defineTool5({
  name: "search_catalog",
  title: "Search Spencer's Cardtopia catalog",
  description: "Search available Magic: The Gathering singles and drops in Spencer's Cardtopia catalog by name. Returns id, name, price, PIX price, discount, quantity in stock and product type.",
  inputSchema: {
    query: z4.string().describe("Text to match against the card/product name."),
    limit: z4.number().int().describe("Max number of results (default 20, max 50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }, ctx) => {
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const trimmed = query.trim();
    if (!trimmed) {
      return { content: [{ type: "text", text: "Empty query" }], isError: true };
    }
    const escaped = trimmed.replace(/[%,]/g, " ");
    const { data, error } = await supabaseForUser5(ctx).from("inventory").select("id,name,price,price_pix,discount,quantity,product_type,category").ilike("name", `%${escaped}%`).gt("quantity", 0).order("name", { ascending: true }).limit(take);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uonzprmsnctldppgrcxo";
var mcp_default = defineMcp({
  name: "spencers-cardtopia-mcp",
  title: "Spencer's Cardtopia",
  version: "0.1.0",
  instructions: "Tools for Spencer's Cardtopia (Magic: The Gathering store). Use `search_catalog` to look up available cards; `list_my_orders` and `get_my_order` to inspect the signed-in customer's orders; `list_my_decks` to read their saved decks; `list_my_favorites` to see favorited cards.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_catalog_default,
    list_my_orders_default,
    get_my_order_default,
    list_my_decks_default,
    list_my_favorites_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
